// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBucX9U4ZVF_sXJi1if_1MVIwIRJSVbiB4',
    appId: '1:409113588739:android:f5d2202b36eef50fca0a36',
    messagingSenderId: '409113588739',
    projectId: 'chat-app-2e630',
    storageBucket: 'chat-app-2e630.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUtM3rS14jdtOVOk41apPBsV7d16yne6Q',
    appId: '1:409113588739:ios:3e813dc9a2eab131ca0a36',
    messagingSenderId: '409113588739',
    projectId: 'chat-app-2e630',
    storageBucket: 'chat-app-2e630.firebasestorage.app',
    androidClientId: '409113588739-fjb7nu7ip3rf0kvjprhc9jgbct413uim.apps.googleusercontent.com',
    iosClientId: '409113588739-imvp8ctktf34vsma1pap2htaqf30k08e.apps.googleusercontent.com',
    iosBundleId: 'com.kareem09.fuelFlow',
  );

}